### PR TITLE
Website for NodeSchool Augusta + some tweaks to the README

### PR DESCRIPTION
**Pull request by dydx**
My first contribution to the NodeSchool Augusta chapter is to craft a maintainable website (and add some more helpful info to the README.

Since I forked this repo and I've been pushing to my own version, there is a demo site you can look at: http://dydx.github.io/augusta/ I sorta like it because it has the NodeJS colors and is relatively simple.

I made a design decision to use Jekyll, as we're fairly limited in "server side" options (ahem.. or lackthereof). Jeykll is a static site generator that works very, very well (I did all of this development work in about three hours, with breaks, and everything behind it is fairly simple once you look at it)

Notes (and I'll put these in the Wiki so everyone can see them more easily later):
- the website is built on Jekyll, you don't necessarily need jekyll installed on your computer to hack on the design, but it sure helps out
- there are three main content types (or collections, if you want to use Jekyll terms). `Events`, `Contributors`, and `Projects`.
- to add a new Event, look at an existing file in the `_events` directory to see how the format goes, then make a new file for the new event (including title, description, and link to the meetup.com (or whatever) page where the event is organized)
- to add a new Contributor, look at an existing file in the `_contributors` directory to see how the format goes, then make a new file for the new contributor (including name, description, github avatar link (sized to 184px with `?s=184` at the end of the URL), and their GitHub page link).
- to add a new Project, look at an existing file in the `_projects` directory to see how the format goes, then make a new file for the new project (including title, description, and github repo link).

kpeeples, I wasn't really sure what to write on your Contributor profile description, please feel free to edit it as you see fit (though don't be overly wordy, the layout doesn't like long text).

One last thing, this is being PR'd to `master`; in order for it to render out, I'm not sure if NodeSchool needs it to be in `gh-pages` or in `master`. If it doesn't show up at nodeschool.io/augusta with this in `master`, then you might need to create a `gh-pages` branch from this branch.

Hope that serves OK, let me know if there are any issues or other things I can do to help.

### CODE REVIEW

**Comment by NorthDecoder** [comment]
Good Job Josh!

Joe Devlin
Nodeschool, Tacoma WA

->-----Original Message-----
->From: Josh Sandlin [mailto:notifications@github.com]
->Sent: Tuesday, June 30, 2015 12:48 AM
->To: nodeschool/augusta
->Subject: [augusta] Website for NodeSchool Augusta + some tweaks to the README (#1)
->
->My first contribution to the NodeSchool Augusta chapter is to craft a maintainable website
->(and add some more helpful info to the README.
->
->Since I forked this repo and I've been pushing to my own version, there is a demo site you can
->look at: http://dydx.github.io/augusta/ I sorta like it because it has the NodeJS colors and
->is relatively simple.
->
->I made a design decision to use Jekyll, as we're fairly limited in "server side" options
->(ahem.. or lackthereof). Jeykll is a static site generator that works very, very well (I did
->all of this development work in about three hours, with breaks, and everything behind it is
->fairly simple once you look at it)
->
->Notes (and I'll put these in the Wiki so everyone can see them more easily later):
->
->\* the website is built on Jekyll, you don't necessarily need jekyll installed on your
->computer to hack on the design, but it sure helps out
->
->\* there are three main content types (or collections, if you want to use Jekyll terms).
->Events, Contributors, and Projects.
->
->\* to add a new Event, look at an existing file in the _events directory to see how the
->format goes, then make a new file for the new event (including title, description, and link to
->the meetup.com (or whatever) page where the event is organized)
->
->\* to add a new Contributor, look at an existing file in the _contributors directory to see
->how the format goes, then make a new file for the new contributor (including name,
->description, github avatar link (sized to 184px with ?s=184 at the end of the URL), and their
->GitHub page link).
->
->\* to add a new Project, look at an existing file in the _projects directory to see how the
->format goes, then make a new file for the new project (including title, description, and
->github repo link).
->
->kpeeples, I wasn't really sure what to write on your Contributor profile description, please
->feel free to edit it as you see fit (though don't be overly wordy, the layout doesn't like
->long text).
->
->Hope that serves OK, let me know if there are any issues or other things I can do to help.
->
->________________________________
->
->
->You can view, comment on, or merge this pull request online at:
->
->
->  https://github.com/nodeschool/augusta/pull/1
->
->
->Commit Summary
->
->
->\* update README.md with some more detailed info about contributors and links
->\* starting on Jekyll port of Pixelarity Axiom template
->\* added theme. porting over to jekyll
->\* working on programmatically listing collections; events and contributors
->\* Have projects and contributors working, just need to get events working OK
->\* front page renders well. it might be worth-while to just add some frontmatter meta for
->events links
->\* ok, got everything reasonably figured out
->
->
->File Changes
->
->
->\* M README.md https://github.com/nodeschool/augusta/pull/1/files#diff-0  (14)
->\* A _config.yml https://github.com/nodeschool/augusta/pull/1/files#diff-1  (21)
->\* A _contributors/josh-sandlin.md
->https://github.com/nodeschool/augusta/pull/1/files#diff-2  (8)
->\* A _contributors/kenneth-peeples.md
->https://github.com/nodeschool/augusta/pull/1/files#diff-3  (8)
->\* A _events/upcoming.md https://github.com/nodeschool/augusta/pull/1/files#diff-4  (6)
->\* A _includes/.gitkeep https://github.com/nodeschool/augusta/pull/1/files#diff-5  (0)
->\* A _includes/meta.html https://github.com/nodeschool/augusta/pull/1/files#diff-6  (2)
->\* A _includes/scripts.html https://github.com/nodeschool/augusta/pull/1/files#diff-7
->(8)
->\* A _layouts/.gitkeep https://github.com/nodeschool/augusta/pull/1/files#diff-8  (0)
->\* A _layouts/contributor.html https://github.com/nodeschool/augusta/pull/1/files#diff-9
->(0)
->\* A _layouts/default.html https://github.com/nodeschool/augusta/pull/1/files#diff-10
->(164)
->\* A _layouts/event.html https://github.com/nodeschool/augusta/pull/1/files#diff-11  (10)
->\* A _layouts/project.html https://github.com/nodeschool/augusta/pull/1/files#diff-12
->(1)
->\* A _projects/hackathon2.md https://github.com/nodeschool/augusta/pull/1/files#diff-13
->(6)
->\* A _site/assets/css/font-awesome.min.css
->https://github.com/nodeschool/augusta/pull/1/files#diff-14  (4)
->\* A _site/assets/css/ie8.css https://github.com/nodeschool/augusta/pull/1/files#diff-15
->(39)
->\* A _site/assets/css/images/toggle.svg
->https://github.com/nodeschool/augusta/pull/1/files#diff-16  (5)
->\* A _site/assets/css/main.css https://github.com/nodeschool/augusta/pull/1/files#diff-17
->(2945)
->\* A _site/assets/font/FontAwesome.otf
->https://github.com/nodeschool/augusta/pull/1/files#diff-18  (0)
->\* A _site/assets/font/fontawesome-webfont.eot
->https://github.com/nodeschool/augusta/pull/1/files#diff-19  (0)
->\* A _site/assets/font/fontawesome-webfont.svg
->https://github.com/nodeschool/augusta/pull/1/files#diff-20  (565)
->\* A _site/assets/font/fontawesome-webfont.ttf
->https://github.com/nodeschool/augusta/pull/1/files#diff-21  (0)
->\* A _site/assets/font/fontawesome-webfont.woff
->https://github.com/nodeschool/augusta/pull/1/files#diff-22  (0)
->\* A _site/assets/font/fontawesome-webfont.woff2
->https://github.com/nodeschool/augusta/pull/1/files#diff-23  (0)
->\* A _site/assets/img/pic05.jpg <https://github.com/nodeschool/augusta/pull/1/files#diff-
->24>  (0)
->\* A _site/assets/img/placeholder.png
->https://github.com/nodeschool/augusta/pull/1/files#diff-25  (0)
->\* A _site/assets/js/ie/PIE.htc <https://github.com/nodeschool/augusta/pull/1/files#diff-
->26>  (96)
->\* A _site/assets/js/ie/html5shiv.js
->https://github.com/nodeschool/augusta/pull/1/files#diff-27  (8)
->\* A _site/assets/js/ie/respond.min.js
->https://github.com/nodeschool/augusta/pull/1/files#diff-28  (6)
->\* A _site/assets/js/jquery.dropotron.min.js
->https://github.com/nodeschool/augusta/pull/1/files#diff-29  (2)
->\* A _site/assets/js/jquery.min.js
->https://github.com/nodeschool/augusta/pull/1/files#diff-30  (5)
->\* A _site/assets/js/jquery.slidertron.min.js
->https://github.com/nodeschool/augusta/pull/1/files#diff-31  (2)
->\* A _site/assets/js/main.js https://github.com/nodeschool/augusta/pull/1/files#diff-32
->(101)
->\* A _site/assets/js/skel.min.js <https://github.com/nodeschool/augusta/pull/1/files#diff-
->33>  (2)
->\* A _site/assets/js/util.js https://github.com/nodeschool/augusta/pull/1/files#diff-34
->(587)
->\* A _site/contributors/josh-sandlin/index.html
->https://github.com/nodeschool/augusta/pull/1/files#diff-35  (0)
->\* A _site/contributors/kenneth-peeples/index.html
->https://github.com/nodeschool/augusta/pull/1/files#diff-36  (0)
->\* A _site/events/upcoming/index.html
->https://github.com/nodeschool/augusta/pull/1/files#diff-37  (10)
->\* A _site/index.html https://github.com/nodeschool/augusta/pull/1/files#diff-38  (179)
->\* A _site/projects/hackathon2/index.html
->https://github.com/nodeschool/augusta/pull/1/files#diff-39  (1)
->\* A assets/.gitkeep https://github.com/nodeschool/augusta/pull/1/files#diff-40  (0)
->\* A assets/css/.gitkeep https://github.com/nodeschool/augusta/pull/1/files#diff-41  (0)
->\* A assets/css/font-awesome.min.css
->https://github.com/nodeschool/augusta/pull/1/files#diff-42  (4)
->\* A assets/css/ie8.css https://github.com/nodeschool/augusta/pull/1/files#diff-43  (39)
->\* A assets/css/images/toggle.svg <https://github.com/nodeschool/augusta/pull/1/files#diff-
->44>  (5)
->\* A assets/css/main.css https://github.com/nodeschool/augusta/pull/1/files#diff-45
->(2945)
->\* A assets/font/.gitkeep https://github.com/nodeschool/augusta/pull/1/files#diff-46  (0)
->\* A assets/font/FontAwesome.otf <https://github.com/nodeschool/augusta/pull/1/files#diff-
->47>  (0)
->\* A assets/font/fontawesome-webfont.eot
->https://github.com/nodeschool/augusta/pull/1/files#diff-48  (0)
->\* A assets/font/fontawesome-webfont.svg
->https://github.com/nodeschool/augusta/pull/1/files#diff-49  (565)
->\* A assets/font/fontawesome-webfont.ttf
->https://github.com/nodeschool/augusta/pull/1/files#diff-50  (0)
->\* A assets/font/fontawesome-webfont.woff
->https://github.com/nodeschool/augusta/pull/1/files#diff-51  (0)
->\* A assets/font/fontawesome-webfont.woff2
->https://github.com/nodeschool/augusta/pull/1/files#diff-52  (0)
->\* A assets/img/.gitkeep https://github.com/nodeschool/augusta/pull/1/files#diff-53  (0)
->\* A assets/img/pic05.jpg https://github.com/nodeschool/augusta/pull/1/files#diff-54  (0)
->\* A assets/img/placeholder.png <https://github.com/nodeschool/augusta/pull/1/files#diff-
->55>  (0)
->\* A assets/js/.gitkeep https://github.com/nodeschool/augusta/pull/1/files#diff-56  (0)
->\* A assets/js/ie/PIE.htc https://github.com/nodeschool/augusta/pull/1/files#diff-57
->(96)
->\* A assets/js/ie/html5shiv.js https://github.com/nodeschool/augusta/pull/1/files#diff-58
->(8)
->\* A assets/js/ie/respond.min.js <https://github.com/nodeschool/augusta/pull/1/files#diff-
->59>  (6)
->\* A assets/js/jquery.dropotron.min.js
->https://github.com/nodeschool/augusta/pull/1/files#diff-60  (2)
->\* A assets/js/jquery.min.js https://github.com/nodeschool/augusta/pull/1/files#diff-61
->(5)
->\* A assets/js/jquery.slidertron.min.js
->https://github.com/nodeschool/augusta/pull/1/files#diff-62  (2)
->\* A assets/js/main.js https://github.com/nodeschool/augusta/pull/1/files#diff-63  (101)
->\* A assets/js/skel.min.js https://github.com/nodeschool/augusta/pull/1/files#diff-64
->(2)
->\* A assets/js/util.js https://github.com/nodeschool/augusta/pull/1/files#diff-65  (587)
->\* A index.html https://github.com/nodeschool/augusta/pull/1/files#diff-66  (3)
->\* A lib/.gitkeep https://github.com/nodeschool/augusta/pull/1/files#diff-67  (0)
->
->
->Patch Links:
->
->
->\* https://github.com/nodeschool/augusta/pull/1.patch
->\* https://github.com/nodeschool/augusta/pull/1.diff
->
->—
->Reply to this email directly or view it on GitHub
->https://github.com/nodeschool/augusta/pull/1 .
-><https://github.com/notifications/beacon/AJJ0OO_xt6yAWNNmKpqNr6CW8E0Bbh0Vks5oYkFLgaJpZM4FOwg5.
->gif>

**Comment by dydx** [comment]
Thanks!

**Comment by kpeeples** [comment]
Awesome Josh and agree Joe.  I merged the pull request.  2 questions:
1. Josh if acceptable I will go ahead and add you to the team for
read/write access so you can feel free to make updates live.
2. What do I need to do to make the website live,
http://nodeschool.io/augusta/

**Comment by fmoliveira** [comment]
@dydx What an awesome job, it's a very clean and readable design! Congratulations! :)

@kpeeples To make the website live you should merge it to the "gh-pages" branch. Then you could delete nearly everything from the master branch, leaving only the README.md file.

**Comment by kpeeples** [comment]
thanks and will do the following workflow so let me know if you see a better workflow:
git add .
git status // to see what changes are going to be commited
git commit -m 'Some descriptive commit message'
git push origin master

Now for gh-pages:

git checkout gh-pages // go to the gh-pages branch
git rebase master // bring gh-pages up to date with master
git push origin gh-pages // commit the changes
git checkout master // return to the master branch

**Comment by dydx** [comment]
master should be up to date if you've merged my PR; I think what I'd do (which is not necessarily the most correct way), is just:

`git checkout -b gh-pages`
`git push origin gh-pages`

Since `master` isn't really necessary in this instance, just creating a branch for `gh-pages` and leaving it alone would suffice (as `gh-pages` where the bulk of things are at).

**Comment by kpeeples** [comment]
Thanks Josh.  Ran the commands and http://nodeschool.io/augusta/ is accessible now.  Good work on this.  Now to plan the first event.

**Comment by NorthDecoder** [comment]
Hi Ken,

I have had very good response by organizing with http://www.meetup.com/Tacoma-JS/ .
There is some cost, however, once the meetup is ongoing, a few dollars donation at
each meeting will help cover the fee.  Every six months I use a one-time only
debit card that keeps meetup.com out of my personal and business account.  I can
also present the receipt to our sponsors.

We started with zero members last October and had 30 people sign up right away.
Since then we have had a steady trickle of new members, including Jeremy Foster
http://codefoster.com/ who presented an internet of things discussion.  In
retrospect I have added a qualifying question "What is your public github account?"
to the membership permission to see who is really interested and not just selling
real estate.

I have created a presentation pattern that is published at:
http://vividventures.biz/d/?q=javascript
And also at:
http://www.slideshare.net/JoeDevlin2/presentations

Publishing to slideshare just before the presentation allows the attendees to
follow along and to be able to quickly click on the links to download code as
we are preparing to work on it.  Of course the same is true of publishing to
github.

We have aimed for interactive sessions where each person has a laptop and is
coding as we are presenting.  We look at a slide or two then each attendee works
on getting their version of the code working.  This method leads to interaction
between the members. If one person walks around looking at screens, usually me,
to see what is going on and who is stuck and to help debug over the shoulder.
You will also find out who the quietly prolific, really bright coders are too.
They might even do a presentation.  We also ask what IDE, editors, operating
systems etc people are working with.  The real hackers have some amazing
cloodges that they will show off if asked.

There is a high percentage of 'no show', around 50%.  People who RSVP yes but
then cannot come for some reason.  This makes planning food difficult.  I am
trending toward prepackaged snacks that will last past the event day if uneaten.

Keep up the good work.

Joe Devlin
Business Systems Analyst
Vivid Ventures LLC
PH: 253-565-6453
joe@vividventures.biz
demo.vvcrm.biz
meetup.com/Tacoma-JS

->-----Original Message-----
->From: Kenneth Peeples [mailto:notifications@github.com]
->Sent: Tuesday, June 30, 2015 7:48 PM
->To: nodeschool/augusta
->Cc: Joe Devlin
->Subject: Re: [augusta] Website for NodeSchool Augusta + some tweaks to the README (#1)
->
->Thanks Josh. Ran the commands and http://nodeschool.io/augusta/ is accessible now. Good work
->on this. Now to plan the first event.

**Pull request merged**
